### ISSUE TITLE
Search log panic

### ISSUE THREAD

**Issue by crazycs520** [pingcap/sysutil#29]
```go
panic: runtime error: index out of range [512] with length 512
goroutine 759257 [running]:
github.com/pingcap/sysutil.readLastLines(0xc1dc657278, 0x12bffcce, 0xc289794340, 0x0, 0x0, 0xc21d88c000)
/home/jenkins/agent/workspace/idb_multi_branch_v4.0.8-20210726/go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20200715082929-4c47bcac246a/search_log.go:210 +0x366
github.com/pingcap/sysutil.readLastValidLog(0xc1dc657278, 0xa, 0xc1f442b3c0, 0x0, 0x0)
/home/jenkins/agent/workspace/idb_multi_branch_v4.0.8-20210726/go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20200715082929-4c47bcac246a/search_log.go:144 +0xe5
github.com/pingcap/sysutil.resolveFiles.func1(0xc1c517b400, 0x36, 0x37949c0, 0xc289794270, 0x0, 0x0, 0x121e929, 0xc289794270)
/home/jenkins/agent/workspace/idb_multi_branch_v4.0.8-20210726/go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20200715082929-4c47bcac246a/search_log.go:83 +0x37f
path/filepath.walk(0xc1c517b400, 0x36, 0x37949c0, 0xc289794270, 0xc4d2b5f9c0, 0x0, 0x0)
/usr/local/go/src/path/filepath/path.go:358 +0x425
path/filepath.walk(0x7ffc87348f0c, 0x15, 0x37949c0, 0xc1de149450, 0xc4d2b5f9c0, 0x0, 0x7ffc87348f0c)
/usr/local/go/src/path/filepath/path.go:382 +0x2ff
path/filepath.Walk(0x7ffc87348f0c, 0x15, 0xc10c5dc9c0, 0x4, 0x15ff97b)
/usr/local/go/src/path/filepath/path.go:404 +0xff
github.com/pingcap/sysutil.resolveFiles(0x7ffc87348f0c, 0x1e, 0x17af5211580, 0x17af52ed120, 0x0, 0x0, 0x0, 0x0, 0x0)
/home/jenkins/agent/workspace/idb_multi_branch_v4.0.8-20210726/go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20200715082929-4c47bcac246a/search_log.go:54 +0x1be
github.com/pingcap/sysutil.(*DiagnosticsServer).SearchLog(0xc01464fe60, 0xc150009490, 0x3798a40, 0xc1de123df0, 0x0, 0x0)
/home/jenkins/agent/workspace/idb_multi_branch_v4.0.8-20210726/go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20200715082929-4c47bcac246a/service.go:45 +0x94
github.com/pingcap/kvproto/pkg/diagnosticspb._Diagnostics_SearchLog_Handler(0x31d8760, 0xc0123396b0, 0x37946c0, 0xc1de2b1e00, 0
```

**Comment by zyguan** [comment]
another case, full log can be accessed [here](http://minio.pingcap.net:9000/tp-team/builds/2021-12-28/tipocket-ledger1-v40-1640721600/tipocket-ledger1-v40-1640721600/output.tgz).
```
github.com/pingcap/sysutil.(*DiagnosticsServer).SearchLog.func1(0xc01ce15be0)
        /go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20210730114356-fcd8a63f68c5/service.go:45 +0xa1
panic(0x31b5360, 0xc026fa0f40)
        /usr/local/go/src/runtime/panic.go:679 +0x1b2
github.com/pingcap/sysutil.parseLogItem(0xc0249fcc55, 0x20, 0xc026d98898, 0xa2db000, 0xc02701b140)
        /go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20210730114356-fcd8a63f68c5/search_log.go:308 +0x79c
github.com/pingcap/sysutil.readLastValidLog(0x3916a60, 0xc0266eb980, 0xc026d98898, 0xa, 0xc027086ac0, 0x0, 0x0)
        /go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20210730114356-fcd8a63f68c5/search_log.go:178 +0x8f
github.com/pingcap/sysutil.resolveFiles.func1(0xc026654f40, 0x19, 0x3933c40, 0xc0267352b0, 0x19, 0x0)
        /go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20210730114356-fcd8a63f68c5/search_log.go:89 +0x3ec
github.com/pingcap/sysutil.resolveFiles(0x3916a60, 0xc0266eb980, 0x7ffec6d0256f, 0x19, 0x17e034ac1d0, 0x17e034bac30, 0x0, 0x0, 0x0, 0x0, ...)
        /go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20210730114356-fcd8a63f68c5/search_log.go:113 +0x319
github.com/pingcap/sysutil.(*DiagnosticsServer).SearchLog(0xc0004d0ec0, 0xc02691b730, 0x39380e0, 0xc026775b80, 0x0, 0x0)
        /go/pkg/mod/github.com/pingcap/sysutil@v0.0.0-20210730114356-fcd8a63f68c5/service.go:59 +0x12d
github.com/pingcap/kvproto/pkg/diagnosticspb._Diagnostics_SearchLog_Handler(0x334e1c0, 0xc000ab26c0, 0x3933940, 0xc0263d4f00, 0x555d450, 0xc0253a5400)
        /go/pkg/mod/github.com/pingcap/kvproto@v0.0.0-20210308075244-560097d1309b/pkg/diagnosticspb/diagnosticspb.pb.go:633 +0x109
google.golang.org/grpc.(*Server).processStreamingRPC(0xc0009ebc80, 0x39429a0, 0xc02655a900, 0xc0253a5400, 0xc000ab27b0, 0x4f8cb40, 0x0, 0x0, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1237 +0xb42
google.golang.org/grpc.(*Server).handleStream(0xc0009ebc80, 0x39429a0, 0xc02655a900, 0xc0253a5400, 0x0)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:1317 +0xd30
google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0267ea910, 0xc0009ebc80, 0x39429a0, 0xc02655a900, 0xc0253a5400)
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:722 +0xbb
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /go/pkg/mod/google.golang.org/grpc@v1.26.0/server.go:720 +0xa1
```
